feat(api): added reports
oasis-sh/oasis pull request #365
Opened 2021-06-04 21:39 UTC by BronzW

2021-06-05 13:54 UTC, heybereket approved these changes

2021-06-05 13:54 UTC, HenryLeC commented
I will review in a min

2021-06-05 13:59 UTC, HenryLeC requested changes
Just a few changes

2021-06-05 13:59 UTC, HenryLeC commented on packages/api/schema.gql
> +  type: String!
Make this a report type

2021-06-05 13:59 UTC, HenryLeC commented on packages/api/src/modules/reports/GetQueue.resolver.ts
> +  @Authorized()
Can you make this authorized with either admin or mod role

2021-06-05 13:59 UTC, HenryLeC commented on packages/api/src/modules/reports/GetQueue.resolver.ts
> +      relations: ['accuse', 'reporter'],
This isn't needed if they are promises

2021-06-05 13:59 UTC, HenryLeC commented on packages/api/src/modules/reports/MarkAsResolved.resolver.ts
> +  @Authorized()
Again mod or admin

2021-06-05 15:05 UTC, HenryLeC commented
I really don't like merging when I can't test so I will test it when I get home and then merge

2021-06-05 15:08 UTC, BronzW commented
> I really don't like merging when I can't test so I will test it when I get home and then merge

do so

2021-06-06 16:08 UTC, HenryLeC approved these changes

2021-06-06 16:08 UTC, merged